Modification
WildCodeSchool/purple-php-2109-project2-mybooks pull request #1
Opened 2021-11-08 08:23 UTC by Thomas905

2021-11-08 08:45 UTC, mcbeloy approved these changes, later dismissed

2021-11-08 08:56 UTC, go37 submitted a review, later dismissed

2021-11-08 16:10 UTC, RomainClair requested changes
You should not change the AbstractManager (unless you find a bug in it) because it's your framework.
Furthermore, because you removed selectAll and selectOneById, you had to recreate them all many times in every *Manager class and that probably is uncessary work.
The best practice is to use singular for SQL tables (author, editor, ...) and to have the same for classes (Author, Editor, therefore AuthorManager, EditorManager...)

2021-11-08 16:10 UTC, RomainClair commented on src/Model/BooksManager.php
> +    }
This clearly does not belong in a manager class

2021-11-10 09:08 UTC, RomainClair requested changes
We probably shouldn't change the abstractManager because it's our framework.

2021-11-10 09:08 UTC, RomainClair commented on src/Model/AbstractManager.php
> +    }
This method should probably be in the bookManager because it return a book

2021-11-11 16:35 UTC, go37 submitted a review, later dismissed
ok for me

2021-11-11 16:38 UTC, alexandregrue requested changes

2021-11-11 16:38 UTC, alexandregrue commented on src/routes.php
> +    '' => ['BookController', 'index',]
Invert line 11 and 12

2021-11-11 16:38 UTC, alexandregrue commented on src/Model/BookManager.php
> +use PDO;
Book extends of Abstract manager so don't need use PDO

2021-11-11 17:21 UTC, alexandregrue approved these changes, later dismissed

2021-11-12 08:41 UTC, RomainClair requested changes

2021-11-12 08:41 UTC, RomainClair commented on src/Controller/BookController.php
> +        }
There's nearly no user input verification...

2021-11-15 08:55 UTC, go37 commented
In BookManager.php, change "Book" by "book" in line 24 and 72.

2021-11-15 08:57 UTC, go37 commented on src/Model/BookManager.php
> +        JOIN format ON Book.format_id = format.id
book.format_id

2021-11-15 08:57 UTC, go37 commented on src/Model/BookManager.php
> +        JOIN format ON Book.format_id = format.id
book.format_id

2021-11-16 15:10 UTC, go37 approved these changes, later dismissed
good

2021-11-17 11:09 UTC, go37 submitted a review, later dismissed
ok for me

2021-11-17 13:22 UTC, mcbeloy approved these changes

2021-11-17 13:22 UTC, mcbeloy commented on src/Model/BookManager.php
>      /* Insert element aboot the book into bdd */
"aboot" is "about"...

2021-11-17 13:23 UTC, mcbeloy approved these changes

2021-11-17 13:23 UTC, mcbeloy submitted a review, later dismissed

2021-11-17 13:25 UTC, mcbeloy approved these changes

2021-11-17 13:25 UTC, mcbeloy approved these changes

2021-11-17 13:29 UTC, mcbeloy approved these changes

2021-11-17 14:00 UTC, RomainClair approved these changes
The user's input checks (form) are still not sufficient enough

2021-11-17 14:00 UTC, merged