first commit show book id
WildCodeSchool/purple-php-2109-project2-mybooks pull request #2
Opened 2021-11-08 08:26 UTC by mcbeloy

2021-11-08 08:31 UTC, Thomas905 submitted a review, later dismissed

2021-11-08 08:32 UTC, CECDO submitted a review, later dismissed

2021-11-08 10:48 UTC, Thomas905 approved these changes, later dismissed

2021-11-08 16:04 UTC, RomainClair requested changes
You probably should add some checks for invalid ids (book not in the database for instance)

2021-11-08 16:04 UTC, RomainClair commented on src/Controller/BooksController.php
> +        $show = $booksManager->selectOneById($id);
The $show variable should probably be $book because it contains a book

2021-11-08 16:04 UTC, RomainClair commented on src/Model/BooksManager.php
> +class BooksManager extends AbstractManager
This class should be a BookManager and not a BooksManager (because it deal with the book table)

2021-11-08 16:04 UTC, RomainClair commented on src/Model/BooksManager.php
> +    public function selectOneById(int $id)
You probably shouldn't redefine the AbstractManager::selectOneById method because you could need it.. You could probably named this one selectOneCompleteBookById... or selectOneByIdWithEditorCategoryFormatEmplacementAuthorAndStatus
And by the way, the english for "emplacement" is location.

2021-11-10 09:07 UTC, mcbeloy commented
corrections done on BookController, BookManager and function's name in BookManager.

2021-11-11 10:37 UTC, alexandregrue requested changes
You have BookControler, BooksController and BookManager and BooksManager with the same thing in each. I think you need to remove the BooksManager and BookControler.

2021-11-13 15:01 UTC, alexandregrue requested changes
The test doesn't work, you need to give a parameter to your method to selelct book information about the ID. Moreover u need to implement verification for the id that you going take. What append if it's not a number or empty

2021-11-16 15:15 UTC, go37 submitted a review, later dismissed
ok

2021-11-17 10:39 UTC, go37 approved these changes
ok for me

2021-11-17 10:41 UTC, alexandregrue approved these changes
the fonctionnality for recap and delete work correctly

2021-11-17 11:09 UTC, RomainClair approved these changes

2021-11-17 11:09 UTC, merged