Us1 add book
WildCodeSchool/purple-php-2109-project2-mybooks pull request #5
Opened 2021-11-09 16:16 UTC by alexandregrue

2021-11-09 16:29 UTC, go37 submitted a review, later dismissed

2021-11-11 10:34 UTC, go37 approved these changes, later dismissed
ok for me. great job !

2021-11-12 09:10 UTC, RomainClair requested changes
This PR is not atomic.
You should break it into a : 
- add author
- add editor
- add location, etc...
- and the add book

Therefore it's very hard to review
Furthermore, it's almost impossible to test because the addBook pages display white buttons on a white background.

You probably should consider hosting you assets (fonts) on your website.
One of the consequence is that your site will not depend on external internet ressources, so it will work during offline demos.

I guess the cover_page images are the result of testing so they should probably be in the .gitignore and not in the git repository

Why are there all the book field int the addAuthor form ?

2021-11-12 09:10 UTC, RomainClair commented on src/Model/AuthorsManager.php
> +    } */
There shouldn't be dead code in PRs

2021-11-12 09:10 UTC, RomainClair commented on src/Controller/BooksController.php
> +class BooksController extends AbstractController
Having a BookController and a BooksController class is very confusing. You probably should only have one

2021-11-13 00:09 UTC, Thomas905 submitted a review, later dismissed
good for me modification ask by Romain is OK

2021-11-16 15:22 UTC, Thomas905 submitted a review, later dismissed
ok for me

2021-11-16 16:23 UTC, Thomas905 approved these changes

2021-11-17 08:29 UTC, RomainClair approved these changes

2021-11-17 08:29 UTC, merged