Dashboard design first version & filter for book
WildCodeSchool/purple-php-2109-project2-mybooks pull request #8
Opened 2021-11-12 23:42 UTC by Thomas905

2021-11-12 23:53 UTC, alexandregrue approved these changes, later dismissed
Ok for me, we develop the fonctionnality together, test look ok to filter on one or more elements and obtained the expected result

2021-11-15 08:24 UTC, RomainClair requested changes
.DS_Store must not be in the repository

2021-11-15 08:24 UTC, RomainClair commented on public/assets/js/dashboard.js
> +function myFunction() {
You should use more meaningful names

2021-11-15 08:24 UTC, RomainClair commented on src/Model/FormProcessing.php
> +            ];
You should verify the presence (and emptiness eventually)  of each $_GET field individually

2021-11-16 13:10 UTC, alexandregrue approved these changes

2021-11-17 13:39 UTC, closed without merging